// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojeuqqyjendnuobomxxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZXVxcXlqZW5kbnVvYm9teHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzczMTgsImV4cCI6MjA2MjA1MzMxOH0.jrk20CCLeQYaA2__K5c5Q1KIao7rlndfUwXox5Vr3Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);